### ISSUE TITLE
getTerminalNodeIDs Interpretation

### ISSUE THREAD

**Issue by tchakravarty** [imbs-hl/ranger#126]
Following the example in the documentation: 

```
rf = ranger(Species ~ ., data = iris, num.trees = 5, write.forest = TRUE)
apply(getTerminalNodeIDs(rf, dat = iris), 2, table)
```

which gives this output: 

```
[[1]]

 2  7  9 10 12 13 15 16 18 19 
50  2 39 35  5  2 10  5  1  1 

[[2]]

 2  9 10 13 14 15 16 17 18 19 
50 37 25  8 13  1  9  3  2  2 

[[3]]

 2  6  8 10 13 15 17 20 21 
50 36  3  3 43  4  6  3  2 

[[4]]

 2  5  6  7 
50 48 47  5 

[[5]]

 2  6  7  8  9 
49 42 17 10 32 
```

Basically, terminal nodes appear not to be labeled in sequence, but have labels `{2,  7,  9, 10, 12, 13, 15, 16, 18, 19}`, for example in the first tree. Of course it doesn't matter what the labels of the terminal nodes are, but it is unusual enough for me to ask if I am reading this right, and what the non-sequential labeling means?

**Comment by mnwright** [comment]
The nodes are numbered sequentially at creation. Not all nodes are terminal nodes and therefore they cannot appear in your tables. 
You could try to reconstruct the trees with `rf$forest$child.nodeIDs`. Unfortunately there is currently no better method to extract tree information available, see also #98.

By the way, if you are using the GitHub version of ranger, you could use `predict(rf, type = 'terminalNodes')` instead of `getTerminalNodeIDs`, it's faster.
