### ISSUE TITLE
R session crash when predicting from old ranger model

### ISSUE THREAD

**Issue by caewok** [imbs-hl/ranger#132]
I have a library of ranger models created using ranger 0.3.0. Unfortunately, when using a newer ranger to predict these models, it crashes the entire R session (regardless of whether a try statement is used). I would rather like to not re-create all those models, so does anyone have any suggestions on updating the model files to work with newer versions of ranger? Or perhaps there is a bug here that could be squashed?

The following code results in a hard crash to the R session when predicting a ranger 0.3.0 model using ranger 0.6.0:
# install ranger 0.3.0 from cran

`devtools::install_version(package = "ranger", version="0.3.0", repos = "http://cran.us.r-project.org")
library(ranger)
# prediction

train.idx <- sample(nrow(iris), 2/3 \* nrow(iris))
iris.train <- iris[train.idx, ]
iris.test <- iris[-train.idx, ]
rg.iris <- ranger(Species ~ ., data = iris.train, write.forest = TRUE)
pred.iris <- predict(rg.iris, dat = iris.test)
table(iris.test$Species, pred.iris$predictions)
# save the model

saveRDS(rg.iris, file="ranger_test.rds")
# restart R session and then switch to newer ranger version

quit(save = "no")
devtools::install_version(package = "ranger", version="0.6.0", repos = "http://cran.us.r-project.org")
library(ranger)

train.idx <- sample(nrow(iris), 2/3 \* nrow(iris))
iris.train <- iris[train.idx, ]
iris.test <- iris[-train.idx, ]
rg.iris <- readRDS("ranger_test.rds")
pred2.iris <- predict(rg.iris, dat = iris.test)`  # crash

**Comment by mnwright** [comment]
In ranger 0.3.9 the `child.nodeIDs` where changed. In the old version there was 1 list per tree, containing vectors of size 0 (terminal node) or 2 (left and right childs). In the new version it's a list of two vectors (left and right childs) containing child node IDs or 0 for terminal nodes. Due to the way R saves lists of vectors the new approach saves a lot of memory. 

A crude hack to convert your forest could be something like
```R
rg.iris$forest$child.nodeIDs <- lapply(rg.iris$forest$child.nodeIDs, function(x) {
  x[sapply(x, length) == 0] <- 0
  as.list(data.frame(do.call(rbind, x)))
})
```
I'm sure there are more efficient solutions. ;)
