### ISSUE TITLE
What do these values mean in result$forest?

### ISSUE THREAD

**Issue by rfcv** [imbs-hl/ranger#147]
@mnwright 
Run the sample code to get a ranger forest object:
```
library(ranger)
e10=as.data.frame(NA)
for(i in 1:11){
  set.seed(i)
  e10[1:10,i]=sample(1:10)
}
e10[,1]=100:109
names(e10)=paste0("V",1:11)

result=ranger(V1~.,data=e10,num.trees=10,mtry=1,min.node.size=0)

result$forest$child.nodeIDs
result$forest$split.varIDs
result$forest$split.values
```

When inspecting the model, I noticed two things that I hope you can clear up. 

First: mtry is set to 1, which means each tree in `result$forest$split.varIDs` should only have one non-zero integer. Does this mean that the column numbers change as we go down the tree? As you can see below, the first tree tries columns 5, 8 and 10.

Second: What does it mean when a non-zero value is followed by a non-zero value in `result$forest$split.varIDs`? For example: 
```
result$forest$split.varIDs
[[1]]
[1]  5  0  8 10  0  0  0

result$forest$split.values
[[1]]
[1]   2.0 108.5   3.0   3.0 105.5 100.0 102.0
```
It's as if there was no value assigned to the split involving column 8.

**Comment by mnwright** [comment]
#### General information
`child.nodeIDs` is a list containing two vectors for each tree. These are the child node IDs for each node in the tree. The left children in the first vector, the right children in the second vector. The nodeIDs are 0-indexed. However, since the root of a tree (ID 0) cannot be a child, the 0 is used for terminal nodes. 

In `split.varIDs` there is a vector for each tree with the splitting variables for each node in the tree. These IDs are 0-indexed, too. If you use the formula interface, the 0-variable should be the outcome. Terminal nodes also have a 0 here. 

In `split.values` the splitting values for all nodes are saved. In terminal nodes, the outcome for this node ist saved in `split.values`.

#### Your questions
> First: mtry is set to 1, which means each tree in result$forest$split.varIDs should only have one non-zero integer. Does this mean that the column numbers change as we go down the tree? As you can see below, the first tree tries columns 5, 8 and 10.

With `mtry = 1`, one variable is tried in each split. It's not the same variable in an entire tree. 

> Second: What does it mean when a non-zero value is followed by a non-zero value in result$forest$split.varIDs? For example:

I'm afraid I'm not understanding the question. Maybe this is answered by the description above? 

Note: A 0 in `split.varIDs` is no sufficient condition for a terminal node. Check `child.nodeIDs` to be sure. 

We really need #98.

**Comment by rfcv** [comment]
About `mtry = 1`, that was my misunderstanding of the RF algorithm. I thought `mtry` was the same for the whole tree. 
Here is the first tree from the above model:
```
[1]    1     0     3     5     0     0     0    #left child
[1]    2     0     4     6     0     0     0    #right child
[1]    5     0     8     10    0     0     0    #split column ID
[1]    2.0   108.5 3.0   3.0   105.5 100.0 102.0    #split value
```
So walking down this tree, we take our first split on column 5, which is at a value of 2.0, and if it is less than 2.0, we predict 108.5 (I think). Because of the zero in child, this is a terminal node. Then, we select column 8, and we split it at 3.0, and we immediately split again at 10? Which of those y-hat split values corresponds to these splits? 

Finally, for #98, check out this user:
https://github.com/sorhawell
http://stats.stackexchange.com/users/49132/soren-havelund-welling

Maybe with some porting to accept ranger forests, you could utilize his package forestFloor for model interpretation.

**Comment by mnwright** [comment]
I've drawn a tree based on your model: https://www.draw.io/i/2p0zoPG

About forestFloor: I was in contact with Søren about a year ago and there was some experimental support for ranger, but I'm not sure what's the status now.

**Comment by rfcv** [comment]
Thanks much. So to be sure: left nodes are less than, and right nodes are greater than or equal to?

**Comment by mnwright** [comment]
Left nodes are less or equal, right nodes are greater than.
