### ISSUE TITLE
maxstat split rule

### ISSUE THREAD

**Issue by gk76** [imbs-hl/ranger#266]
I noticed that using as plitting method maxstat it does run multicore. (maybe also for extratrees)
It is not possible to parallelize using this rule or is something that will be implemented.

Moreover I cannot have results in accettable time using as rule C on a dataset of 45000 data and mtry 4.
Even 1 tree does not return nothing after hours

I tried with 500 trees and in that case, as should be, it use 100% of my 64 logical cores but of course no result in acceptable time
Best
g

**Comment by mnwright** [comment]
I'm not sure I understand your question. All split rules run multithreaded. However, the multithreading is implemented tree-wise so you won't benefit for single trees. 
Yes, the `"C"` splitting is very slow, in particular for many observations because all pairs are compared. For larger datasets you should probably use `"logrank"` or `"maxstat"`.
