### ISSUE TITLE
Large forest files

### ISSUE THREAD

**Issue by dancooke** [imbs-hl/ranger#303]
Ranger seems to produce very large forest files compared to to scikit-learn's implementation - at least for classification (Gb's vs Mb's). I think the forest file format could be improved to reduce file size. For example, it seems class counts are currently stored as binary `double`s, but really these should be integer types?

**Comment by mnwright** [comment]
This probably applies only to the pure C++ version.
Do you think the problem is inefficient serialization? Or does scikit-learn use a clever trick to save the forest? A simple improvement would be to use compression. The current way the forests are saved is very simple and not optimized at all because it's not needed in the R version.

**Comment by sipemu** [comment]
When applying survival analysis the forest, especially chf, gets large. It is not possible to train apply survival random forest with 25,000 objects with write.orest = T on a standard machine.

**Comment by mnwright** [comment]
This is expected behaviour for survival forests, see [#202](https://github.com/imbs-hl/ranger/issues/202#issuecomment-313449199). We have to save the CHF of each terminal node to be able to predict. 

Your only option is probably to reduce the number of time points, also described in [#202](https://github.com/imbs-hl/ranger/issues/202#issuecomment-313876174).

**Comment by sipemu** [comment]
@mnwright Thank you. I will give it a try.

**Comment by dancooke** [comment]
@mnwright How are forest files saved in the R version? I haven't gone through the serialisation in detail so I'm not sure what other improvements could be made (other than the class count type). Probably there are similar issues elsewhere as the classification forest files without class counts are quite large too. I don't think scikit does anything special - it just uses the `pickle` serialisation package.

**Comment by AFerradji** [comment]
Hi, thank you for this interesting package!
I'm trying to run survival random forest with maxstat split rule (Sample size of 110k with 550 features) but unfortunately the program crashes after 17%... I got the following log (please see attached, i'm not conforatble with C++ programing). I would like to know if it's a memory problem (i have 8Gb of memory in my computer). Could you provid a .exe for windows. Thank you in advance.
![ranger](https://user-images.githubusercontent.com/37197200/39973376-3496f57a-56ed-11e8-9f18-4251bf376e73.JPG)

**Comment by mnwright** [comment]
@dancooke They are converted to R lists with Rcpp, see https://github.com/imbs-hl/ranger/blob/e770dfe2f0a9fb324944351e36c550ce9e4174da/src/rangerCpp.cpp#L230

I'll look into the serialization and maybe compare with scikit-learn. 

@AFerradji As explained in [#202](https://github.com/imbs-hl/ranger/issues/202#issuecomment-313449199) this is a general problem in survival forests because a cumulative hazard function has to be saved in each terminal node. There is also a possible solution there (but I'm not sure whether it will be possible to analyze your dataset on a 8GB machine). Please post in #202 if you have further questions specific to survival forests.

**Comment by dancooke** [comment]
@mnwright Ah. Does it not make more sense to have a single forest file format that is shared by both the C++ and R versions?

**Comment by mnwright** [comment]
I don't think so. In R the forest is kept in memory and in C++ it is saved to disk. Most R users will use `saveRDS()` or similar to save the forest to disk in compressed format but want to use R to look into it (while in memory).

**Comment by dancooke** [comment]
Looks like I made a mistake - I must have been comparing with different tree depths. I guess this issue can be closed, although might be worth keeping open as the point I made about `double`s being used for class counts remains valid.

**Comment by mnwright** [comment]
OK. Are you referring to [terminal_class_counts](https://github.com/imbs-hl/ranger/blob/735d457f6fc55435f0e897f2ca450b906691fd03/src/TreeProbability.cpp#L78)? The name is misleading (at least) because we are [saving proportions there](https://github.com/imbs-hl/ranger/blob/735d457f6fc55435f0e897f2ca450b906691fd03/src/TreeProbability.cpp#L61). We should rename it!
