### ISSUE TITLE
Compilation fails with c++ 14

### ISSUE THREAD

**Issue by klickagent** [imbs-hl/ranger#376]
When I try to compile the ranger package using the c++ compiler 14 I do get the following error because the make_unique function is ambiguous.

ForestClassification.cpp:41:9: error: call to 'make_unique' is ambiguous

Will there be an updated version soon, or is there any other workaround to compile using the new compiler?

**Comment by mnwright** [comment]
Which OS and compiler are you using? How exactly do you compile ranger?

**Comment by dlong11** [comment]
I see this with the Microsoft Visual Studio 2017 and 2019.   Its an easy fix - if you qualify make_unique with std the errors will go away.  (std::make_unique)

**Comment by mnwright** [comment]
Since C++11 doesn't have `std::make_unique`, we added our own version here: 
https://github.com/imbs-hl/ranger/blob/7b0d33f1e68a5be9d5fbe77aa65b007cfbe04da8/src/utility.h#L503-L534

What would be the recommended way to make it compatible with both C++11 and C++14?

**Comment by dlong11** [comment]
Take a look at this - this may help - https://github.com/abseil/abseil-cpp/blob/256be563447a315f2a7993ec669460ba475fa86a/absl/memory/memory.h

**Comment by crflynn** [comment]
I also ran into this problem when trying to build for windows, for which the compiler is using C++14 by default with seemingly no way to set it explicitly to C++11. Because of the ambiguity I have some code that rewrites all the calls of `make_unique` in ranger source to `ranger::make_unique` and was able to get it to compile.
