### ISSUE TITLE
large sparse matrix results in sample size = 2 and unrealistic OOB error

### ISSUE THREAD

**Issue by chillydog** [imbs-hl/ranger#431]
Hi,

I have a data set with 659533 cases and 5045 inputs and one output in a sparse matrix in R.  All columns contain dichotomous values (0/1).  I want variable importance values for the 5045 inputs.  After 3.5 days of running (28 cores), I get strange results: Sample size = 2 and unrealistically low OOB prediction error of 0.04% and tiny importances.  See below.  What’s wrong?  Am I predicting a bunch of zeros well?  Would setting class.weights somehow help?  Suggestions appreciated.

Incidentally, I took the JSM 2016 course by Andreas and Marvin.  Thanks!

Best,

Jay

> ## Sparse data matrix:
> class(infants.sMat)
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
> ## First column``NAS” is dependent variable:
> dimnames(infants.sMat)[[2]][1]
[1] "NAS"
## Note rare occurrence of 1, mostly 0’s
> table(infants.sMat[,"NAS"])
     0      1 
659533   3820
> ## Remaining 5045 columns are dichotomous 0/1 variables
> ## most of which indicate 1 rarely, too. (not shown)

> library(ranger)
> infant.ranger1<- ranger(data=infants.sMat,
+                       num.trees=500,
+                       mtry=500,
+                       min.node.size=1,
+                       importance="permutation",
+                       save.memory=TRUE,
+                       dependent.variable.name="NAS",
+                       classification=TRUE)

> save(list=c("infant.ranger1"),file = "infant.ranger1.RData")

> infant.ranger1
Ranger result

Call:
 ranger(data = infants.sMat, num.trees = 500, mtry = 500, min.node.size = 1,      importance = "permutation", save.memory = TRUE, dependent.variable.name = "NAS",      classification = TRUE, seed = 20500 + 5150) 

Type:                             Classification 
Number of trees:                  500 
Sample size:                      2 
Number of independent variables:  5045 
Mtry:                             500 
Target node size:                 1 
Variable importance mode:         permutation 
Splitrule:                        gini 
OOB prediction error:             0.04 %

> range(importance(infant.ranger1))
[1] -1.951434e-05  6.194027e-03

**Comment by mnwright** [comment]
> Sample size = 2 

Looks like a bug for sparse data. But it's only used for printing the result and shouldn't affect anything. Will fix it. 

> and unrealistically low OOB prediction error of 0.04%

That's expected for such unbalanced data. Something like a precision recall curve might be the better choice than simple misclassifications. 

> and tiny importances. 

Permutation importances are changes in OOB prediction error. Since you have 0.04%, i.e. 4e-4, the importances are quite large, aren't they? 

> Am I predicting a bunch of zeros well? Would setting class.weights somehow help?

Yes, `class.weights` might help. Note that there are many methods to handle unbalanced data and I think there isn't a single best method. Does anyone know a good review?

> After 3.5 days of running (28 cores)

Some tips for reducing runtime: 
* Don't use `save.memory` if not absolutely necessary memory-wise. It really slows down the training. 
* Sometimes sparse matrices are slower than dense matrices. If you have enough memory, try that out (but stick to `matrix` and `dependent.variable.name`).
* Permutation importance is quite slow, disable for testing or consider `importance = "impurity_corrected"` (see [http://dx.doi.org/10.1093/bioinformatics/bty373)](http://dx.doi.org/10.1093/bioinformatics/bty373).
* Try `replace = FALSE` and setting a `max.depth` or `min.node.size`, but monitor prediction performance.

**Comment by chillydog** [comment]
Thanks for the info.  I’ll look into this and let you know how things go in a few weeks.

Best,

Jay

On Sep 17, 2019, at 11:57 PM, Marvin N. Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Sample size = 2

Looks like a bug for sparse data. But it's only used for printing the result and shouldn't affect anything. Will fix it.

and unrealistically low OOB prediction error of 0.04%

That's expected for such unbalanced data. Something like a precision recall curve might be the better choice than simple misclassifications.

and tiny importances.

Permutation importances are changes in OOB prediction error. Since you have 0.04%, i.e. 4e-4, the importances are quite large, aren't they?

Am I predicting a bunch of zeros well? Would setting class.weights somehow help?

Yes, class.weights might help. Note that there are many methods to handle unbalanced data and I think there isn't a single best method. Does anyone know a good review?

After 3.5 days of running (28 cores)

Some tips for reducing runtime:

  *   Don't use save.memory if not absolutely necessary memory-wise. It really slows down the training.
  *   Sometimes sparse matrices are slower than dense matrices. If you have enough memory, try that out (but stick to matrix and dependent.variable.name).
  *   Permutation importance is quite slow, disable for testing or consider importance = "impurity_corrected" (see http://dx.doi.org/10.1093/bioinformatics/bty373)<https://urldefense.proofpoint.com/v2/url?u=http-3A__dx.doi.org_10.1093_bioinformatics_bty373&d=DwMCaQ&c=l45AxH-kUV29SRQusp9vYR0n1GycN4_2jInuKy6zbqQ&r=zI_qnInFzYljMfgrW4XCCTppKvsJRrkfHDKifJ93E0U&m=uImOoiAzh89-pzD4PCVZK3PS6pS2OuC_KbH2HuEauww&s=pJ6wvuYH5j57fWiMItVNkllF1Y8qg7eZp2FzSeXrfDI&e=>.
  *   Try replace = FALSE and setting a max.depth or min.node.size, but monitor prediction performance.

**Comment by mnwright** [comment]
> Looks like a bug for sparse data. But it's only used for printing the result and shouldn't affect anything. Will fix it.

Fixed.
