### ISSUE TITLE
importance = "impurity", what is this doing when performing regression?

### ISSUE THREAD

**Issue by jhagenauer** [imbs-hl/ranger#489]
Hi,

the documentation says: "The 'impurity' measure ... is the variance of the responses for regression".

What does that exactly mean? Are the OOB samples involved? Where and how is the variance of the response measured?

Thank you!

**Comment by mnwright** [comment]
A good description can be found in [Ishwaran (2015)](http://dx.doi.org/10.1007/s10994-014-5451-2) in Section 2.1 (right in the beginning); that's how it's implemented in ranger. 
OOB data is not used.

**Comment by Huizi949-z** [comment]
Hello, I wonder if a split rule of "variance" is just equivalent to minimizing MSE? Thank you!

**Comment by mnwright** [comment]
Yes, if you use the mean as prediction (in a node), the resulting mse and the sample variance are exactly the same.

**Comment by Tan-Jiahua** [comment]
Sorry for asking a question related to this issue here. I think when using importance = 'impurity' for regression, the calculation of the variable importance of features (variable.importance) in the class ranger is related to the decrease in variances of the response from splitting the corresponding variable. I am wondering how the decrease in variances in different nodes across different trees is summed up. Could you please tell me about that?
I found a description from another package describing this process (total decrease in node impurities from splitting on the variable, averaged over all trees), but I am not sure if ranger implements it similarly.

**Comment by mnwright** [comment]
Yes, this 

> total decrease in node impurities from splitting on the variable, averaged over all trees

is correct.
