### ISSUE TITLE
Support splitrule = "mae"

### ISSUE THREAD

**Issue by lindeloev** [imbs-hl/ranger#529]
I would like to minimize the mean absolute error. In sklearn, you can set `criterion = "mae"`. I propose supporting this in `ranger` as well with `ranger(..., splitrule = "mae")`. Perhaps include support for `splitrule = "mse"` as well as an alias to "variance".

Awesome package, thanks!

**Comment by mnwright** [comment]
Yes, both suggestions are welcome. Any research on when to choose MAE over MSE?

**Comment by lindeloev** [comment]
We use random forest regression to predict the duration of certain courses of action with the goal of choosing the actions that minimize the total duration. Because our cost is linear with duration (not quadratic as for MSE), optimizing for MAE is desirable.

I haven't found research on the properties of using MAE in random forests. [A lot of academic literature use it](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=random+forest+regression+mae+mse+criterion&btnG=), though often blindly, it seems to me.

**Comment by cargomoose** [comment]
yes please, and also enable MAE  with Extratrees. Most of my work requires exact estimation of probabilities or other amounts. These are regression tasks, where the distortion caused by MSE is not helpful.  Incidentally, with Extratrees: why is it a splitting rule in its own right ? Why not just make the number of random split points a parameter available to all splitting rules.

**Comment by mnwright** [comment]
Let's continue in #368.
