### ISSUE TITLE
Prediction error

### ISSUE THREAD

**Issue by zpunit331111111** [imbs-hl/ranger#557]
Hello, I used ranger for quantile regression and found that there is only one out of bag prediction error instead of all quantiles estimated. Is there anyway to calculate oob prediction error for each quantile? Thanks!

**Comment by mnwright** [comment]
You can make OOB predictions for any quantile with e.g.,

````R

library(ranger)
rf <- ranger(mpg ~ ., mtcars, quantreg = TRUE, keep.inbag = TRUE)
predict(rf, type = "quantiles", quantiles = c(.25, .5, .75))$predictions
````

and then you can calculate any measure of quantile prediction error you want to. Out of curiosity, which measure would you use, the quantile loss?

**Comment by zpunit331111111** [comment]
Thanks! Yes, I used the quantile loss to measure the error.

**Comment by CYGUBICKO** [comment]
In survival setting, is there a way to obtain the prediction error (1-C)? For example

```
library(ranger)
library(survival)
fit <- ranger(Surv(time, status)~., data = veteran)
```

I can get prediction error (1-C) from `fit` but suppose I do prediction using a new data set and I want to get the associated error?

```
pred <- predict(fit, data = veteran[1:20, ])
```

**Comment by CYGUBICKO** [comment]
In survival setting, is there a way to obtain the prediction error (1-C)? For example

```
library(ranger)
library(survival)
fit <- ranger(Surv(time, status)~., data = veteran)
```

I can get prediction error (1-C) from `fit` but suppose I do prediction using a new data set and I want to get the associated error?

```
pred <- predict(fit, data = veteran[1:20, ])
```

**Comment by mnwright** [comment]
See #560.

**Comment by markbfernandez** [comment]
@mnwright Your response for calculating OOB quantiles does not agree with @dswatson's comment on issue [288](https://github.com/imbs-hl/ranger/issues/288). Here is an example using mtcars:

`   # Predictions
   fit=ranger(mpg~.,mtcars,quantreg=T,seed=123,keep.inbag=T)
   pred=predict(fit,mtcars,type='quantiles',quantiles=0.5)$predictions
   
   # OOB Predictions
   OOB_index=ifelse(simplify2array(fit$inbag.counts)==0,T,NA)
   tmp=predict(fit,data=mtcars,predict.all=T)$predictions
   predOOB=apply(tmp*OOB_index,MARGIN=1,FUN=function(x) quantile(x,probs=0.5,na.rm=T))
   
   # Compare
   cbind(pred,predOOB)
   plot(pred~predOOB); abline(0,1)`

Related, `fit$predictions` values for regression contain the mean OOB predictions, even when `quantreg=T`. I think this is fine, since we cannot specify the given quantile in `ranger()`. But can the `ranger()` documentation be updated to clarify this?

**Comment by mnwright** [comment]
First, in `pred` you also have inbag observation included. Try the `predict()` call without the `data=` argument to get OOB quantile regression. 

Second, quantile regression forests are not exactly the quantiles of the regression over all trees, see the paper and https://github.com/lorismichel/quantregForest/issues/3 for a description/discussion. That's why the two predictions don't match exactly in your example, even when using OOB quantile regression.
