### ISSUE TITLE
mtry Default Suitability for High-dimensional Data

### ISSUE THREAD

**Issue by DarioS** [imbs-hl/ranger#640]
> mtry: Number of variables to possibly split at in each node. Default is the (rounded down) square root of the number variables.

Is this a good default value? Let's say there are ten thousand genes. The randomly selected genes would be only one hundred. If there are, say, only five hundred informative features in the data set and the remainder have no predictive power, then there is a high probability of missing all of the predictive features in most tries. The original algorithm has the same default but it was developed in an era of much smaller dimension data sets (c.f. Table 1).

![image](https://user-images.githubusercontent.com/631218/193961121-05dfea79-bba7-46c3-ba4e-ee216cf554b2.png)

> ranger is a fast implementation of random forests or recursive partitioning, particularly suited for high dimensional data

I wonder if Leo would have advocated for `sqrt(p)` if the number of input data features was ten thousand.

**Comment by mnwright** [comment]
No, it's not a good default value for high dimensional data. But it is a good default for rather low dimensional data. I do see you point and I always tell people that they should tune the mtry value, particularly on high dimensional data. 
But the problem is, we don't have a better default. Maybe we should add a note to the docs?

**Comment by mnwright** [comment]
Added a note to the docs in #701.
