### ISSUE TITLE
Different predictions based on variable importance setting

### ISSUE THREAD

**Issue by stanlazic** [imbs-hl/ranger#664]
I was under the impression that the variable importance setting (none, impurity, impurity_corrected, permutation) shouldn't affect the model predictions. However, I get different predictions when using impurity_corrected, but only when providing class weights (even though the two classes have the same number of samples).

```
library(ranger)

## generate data
set.seed(123)
d <- data.frame(y = factor(rep(0:1, 250)), matrix(rnorm(500 * 20), nrow = 500, ncol = 20))

## calculate class weights
class_wt <- 1 / prop.table(table(d$y))

## fit models
m_none <- ranger(
    x = d[, -1],
    y = d$y,
    probability = TRUE,
    seed = 123,
    class.weights = class_wt, 
    importance = "none")$predictions[, 2]

m_imp <- ranger(
    x = d[, -1],
    y = d$y,
    probability = TRUE,
    seed = 123,
    class.weights = class_wt, 
    importance = "impurity")$predictions[, 2]

m_imp_cor <- ranger(
    x = d[, -1],
    y = d$y,
    probability = TRUE,
    seed = 123,
    class.weights = class_wt, 
    importance = "impurity_corrected")$predictions[, 2]

m_perm <- ranger(
    x = d[, -1],
    y = d$y,
    probability = TRUE,
    seed = 123,
    class.weights = class_wt, 
    importance = "permutation")$predictions[, 2]

## look at predictions (m_imp_cor differs from others)
head(cbind(m_none, m_imp, m_imp_cor, m_perm))

        m_none    m_imp m_imp_cor   m_perm
[1,] 0.331036 0.331036  0.473002 0.331036
[2,] 0.387721 0.387721  0.465169 0.387721
[3,] 0.389982 0.389982  0.397291 0.389982
[4,] 0.525280 0.525280  0.558875 0.525280
[5,] 0.611832 0.611832  0.468284 0.611832
[6,] 0.682982 0.682982  0.547534 0.682982
```

Is this the correct behaviour?

**Comment by stephematician** [comment]
Nice catch.

When ranger calculates the corrected impurity importance it creates a permutation of the rows (in the data) prior to the construction of all the trees (it doesn't do this for other importance measures). Currently that permutation is generated using the same random number engine as used by tree construction, so tree construction starts from later in the random number sequence than it would otherwise.

One solution might be to create the permutation with its own random number engine, with an optional seed parameter for reproducibility.

**Comment by stanlazic** [comment]
Thanks for the explanation.

That solution would work, but it might be easier to just document this behaviour so users know. I noticed the difference because of a discrepancy between a development model that calculated importance values and a production model that didn't. Others may get caught out with this as well, but in general, I don't think it's much of an issue. Do you think it's better to update the code or only the docs?

Also, using `importance = "impurity_corrected` produced noticeably worse predictions. But I just have results from one dataset so have no idea if this generalises.

**Comment by mnwright** [comment]
In addition to the random number generator, the permuted features in `"impurity_corrected"` change the tree growing and we expect different results. We also expect worse prediction performance (as you observed). That's why predicting with a model created with `importance="impurity_corrected"` shows a warning (you won't see that warning if you only look at OOB predictions, as above). 
So, this is expected behavior but we should improve the docs.

**Comment by stanlazic** [comment]
Great, thanks for the extra information. I'll update the docs with a brief note and make a pull request.
