### ISSUE TITLE
What is the difference between case.weights, class.weights and sample.fraction?

### ISSUE THREAD

**Issue by Ivy-ops** [imbs-hl/ranger#716]
Thanks for creating this wonderful package!  I am using ranger on a classification problem, imbalanced data 900 control vs 100 case.  I saw the previous description of sample.fraction [https://github.com/imbs-hl/ranger/issues/480]),  which is quite clear. As I see sample.fraction = c(0.1, 0.1) will create 100 case and 100 control for bagging. 
As you mentioned here:[https://github.com/imbs-hl/ranger/issues/381]

> There is one option for "classical" weighting: class.weights, which weights the classes in the splitting rule and in the majority voting (if not in probability mode).

Then I try to combine the case.weights and class.weights in analysis, but don't exactly understand what is doing in combination using them. Could you give some guidance on how to set these 3 parameters in imbalanced data classification, what're rf1/rf2/rf3 mean with these settings of the 3 parameters? Thank you!!!

 ```
 rf1 <- ranger(as.formula(formula), data = data, probability = TRUE, importance = 'impurity', 
               seed = 22, class.weights = c(0.1, 0.2), sample.fraction = c(0.4, 0.3),replace = T, keep.inbag = TRUE)
  rf2 <- ranger(as.formula(formula), data = data, probability = TRUE, importance = 'impurity', 
               seed = 22, case.weights = 0.1, replace = T, keep.inbag = TRUE)
  rf3 <- ranger(as.formula(formula), data = data, probability = TRUE, importance = 'impurity', 
               seed = 22, class.weights = c(0.1, 0.3), replace = T, keep.inbag = TRUE)
```

**Comment by mnwright** [comment]
`case.weights` and weights with `sample.fraction` are quite similar. They both change the weights for being selected in a bootstrap sample. `case.weights` needs a weight for each observation in the dataset and will change its bootstrap weights.  `sample.fraction` is essentially doing the same, but giving all observations in a class the same weight. 

`class.weights` changes the splitting rule as in cost cost-sensitive learning (see `?ranger`). 

You can't use  `case.weights` and weights with `sample.fraction` in combination because they are doing the same thing in the end. `class.weights` can be combined with one of the other two.
