### ISSUE TITLE
Major Performance Degradation when mtry Parameter is Large

### ISSUE THREAD

**Issue by DarioS** [imbs-hl/ranger#730]
It is time-consuming evaluating 0.1, 0.25, 0.5, 1.0 `mtry` proportions in cross-validation. Can the algorithm be optimised?

```r
library(ranger)
library(GEOquery)

dataset <- getGEO("GSE212160")[[1]]
measurements <- t(exprs(dataset)) # 770 genes, 1395 patients.
rejection <- factor(phenoData(dataset)[["characteristics_ch1"]])

> system.time(ranger(x = measurements, y = rejection))
   user  system elapsed 
 11.874   0.038   0.365 
> system.time(ranger(x = measurements, y = rejection, mtry = ncol(measurements)))
   user  system elapsed 
259.192   0.035   3.810
```

It is ten-fold longer than the default of 27 variables (square root) when all 770 genes are considered for splitting.

**Comment by mnwright** [comment]
Unfortunately, this is expected behavior. Evaluating potential split points is the major computational burden of RFs and `mtry` has a big (but approx. linear) impact on this. See also Fig. 3D in the [ranger paper](https://www.jstatsoft.org/index.php/jss/article/view/v077i01/v77i01.pdf). 

You could try `splitrule = "extratrees"`; that only evaluates `num.random.splits` (default 1) per variable and could speed up the calculation for high mtry values.

**Comment by DarioS** [comment]
I feared as much.
