### ISSUE TITLE
non-formula interface

### ISSUE THREAD

**Issue by dashaub** [imbs-hl/ranger#93]
Any possibility of adding the ability to call ranger models like this?
```
ranger(x = xData, y = yData)
```
Most other ML algorithms provide this as an option (e.g. randomForest, Rborist, glmnet, xgboost, lm.fit, glm.fit, etc). These interfaces can usually be faster since the formula does not need to be parsed and the data transformed to this form later anyway. Without looking through `rangerCPP()` I can't tell if this would be the case or not.

**Comment by mayer79** [comment]
Its already implemented. In contrast to your proposal, the "data" contains both $x$ and $y$ variables. The $y$ variable is identified by passing `dependent.variable.name`. All other columns are used as $x$:

ranger(dependent.variable.name = "Species", data = iris)

(for classification, you would need to add the option "classification =TRUE").

**Comment by dashaub** [comment]
How about a wrapper something like this then?
```
ranger <- function(x, y, ...){
  ranger(dependent.variable.name = colnames(y)[1], data = cbind(x, y), ...)
}
```

**Comment by mnwright** [comment]
Thanks @mayer79 for your answer. One small addition: `classification =TRUE` is only needed when `data` is a matrix (and therefore the response column can't be a factor). 

The wrapper suggested in the last post would increase the runtime for large dataset by using `cbind`, which we try to avoid by the non-formula interface. 

However, I'm thinking to switch to the x-y interface internally sometime. The current approach is due to the pure C++ version, where it is easier to handle all data in one file.
