### ISSUE TITLE
oobError for single trees

### ISSUE THREAD

**Issue by cwlanyon** [imbs-hl/ranger#97]
Due to the nature of my data I'm generating individual trees using ranger, the reported OOB error is around 17-18% but the confusion matrices look similar to the below

        predicted
true  1  2
   1 40 40
   2 32 44

Generating the OOB error manually (using individual object predictions) shows an error of ~50%, very different to that reported by ranger.

As an aside, is it possible to recombine the trees I'm growing back into a ranger object?

Cheers,
Chris

**Comment by mnwright** [comment]
Currently, for the prediction error, the number of misclassifications is divided by the number of samples instead of the number of samples with a valid OOB prediction. For `num.trees=1` these numbers naturally differ. I should change that with the next version. 

Unfortunately, there is still no function like `combine` to recombine trees or forests.
