### ISSUE TITLE
Function to convert forest in better human readable format

### ISSUE THREAD

**Issue by mnwright** [imbs-hl/ranger#98]
Something like `randomForest::getTree()`. Any other ideas?

**Comment by rfcv** [comment]
I think that the greatest improvement to ranger would be to allow for an implementation of the extra trees, also known as extremely randomized trees algorithm. The addition of options `method = "extratrees"` and `numRandomCuts = x` to `ranger()` would make ranger the only algorithm anyone needs for random forests due to its speed, memory efficiency, and flexibility with the additional splitting method. It would take some quick changes to the tree.cpp files, but I don't think the addition of the extra trees method would be very difficult to add.

**Comment by mnwright** [comment]
@rfcv Please move your comment to #87. We should implement both approaches to select random splits.

**Comment by Zelazny7** [comment]
Is there are way to see the terminal node predictions for each tree? It doesn't look the terminal node predictions are included in the ranger object.

**Comment by mnwright** [comment]
Closing here, see #245.
